server:
  port: 8080

springdoc:
  swagger-ui:
    path: /

user:
  language: en
  country: US

spring:
  application:
    name: ushadow
  data:
    mongodb:
      uri: mongodb://localhost:27017/ushadow
      database: ushadow
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    locale: en_US
    locale-resolver: fixed
